Description: >
  Prometheus.
Resources:
  Prometheus:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Setup Prometheus.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9093
          ToPort: 9093
          CidrIp: 0.0.0.0/0

  EC2Prometheus:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: Prometheus
      KeyName: udacity
      ImageId: ami-0cb4e786f15603b0d
      Tags:
        - Key: Name
          Value: Prometheus
